# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffold < Formula
  desc "Scaffold files in a solid testable and reliable manner"
  homepage "https://github.com/kjuulh/scaffold"
  version "0.1.7"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjuulh/scaffold/releases/download/v0.1.7/scaffold-darwin-amd64"
      sha256 "720d19d3dbba0ed16d2965099518085cce9be7d6c2820130bc6281d8964a76e8"

      def install
        bin.install "scaffold-darwin-amd64" => "scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjuulh/scaffold/releases/download/v0.1.7/scaffold-darwin-arm64"
      sha256 "f17ba7bc8f700e5df85396843ead9eb603907e70932fe38e7b8c773836d9f3bf"

      def install
        bin.install "scaffold-darwin-arm64" => "scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kjuulh/scaffold/releases/download/v0.1.7/scaffold-linux-amd64"
      sha256 "8f6f6d6b426ce10c9d7cbeb4882f30e562ab101a6bcf2d9196af47b08d759c1c"
      def install
        bin.install "scaffold-linux-amd64" => "scaffold"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kjuulh/scaffold/releases/download/v0.1.7/scaffold-linux-arm64"
      sha256 "519af1f8a49c6f4247c1a75434673e9fe95099bf9937e9c4e9ad7d09cef5b7b9"
      def install
        bin.install "scaffold-linux-arm64" => "scaffold"
      end
    end
  end

  def caveats
    <<~EOS
      export SCAFFOLD_REGISTRY to a git url pointing to your scaffold fork
    EOS
  end
end
