# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffold < Formula
  desc "Scaffold files in a solid testable and reliable manner"
  homepage "https://github.com/kjuulh/scaffold"
  version "0.1.1"
  license "MIT"

  depends_on "gh"
  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kjuulh/scaffold/releases/download/v0.1.1/scaffold-darwin-amd64"
      sha256 "201961318e0f9ef40029baaaffbae727675fb71ee0cf0e639403c3993c315fd2"

      def install
        bin.install "scaffold-darwin-amd64" => "scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kjuulh/scaffold/releases/download/v0.1.1/scaffold-darwin-arm64"
      sha256 "6887b3a0ce71eb4e6b64ed66f1716a392b8a6e3a636f31d12458ccdc8741b4e2"

      def install
        bin.install "scaffold-darwin-arm64" => "scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjuulh/scaffold/releases/download/v0.1.1/scaffold-linux-amd64"
        sha256 "643df0523e99e9e557c2449605e269880b5880c4deefce2408b5c472df5fb011"

        def install
          bin.install "scaffold-linux-amd64" => "scaffold"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kjuulh/scaffold/releases/download/v0.1.1/scaffold-linux-arm64"
        sha256 "ce2b0b586392ddf1f464cdbaae5760afb2e5582b26834773ea482cd297558899"

        def install
          bin.install "scaffold-linux-arm64" => "scaffold"
        end
      end
    end
  end

  def caveats
    <<~EOS
      export SCAFFOLD_REGISTRY to a git url pointing to your scaffold fork
    EOS
  end
end
